import { Brand, ContentTypeConfig, GeneratedContent } from "./types";

export const brandsList: Brand[] = [
  {
    id: "goairclass",
    name: "GoAirClass",
    handle: "@goairclass",
    industry: "Travel & Luxury Aviation",
    voice: "Sophisticated, Adventurous, Exclusive",
    avatar: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=160&auto=format&fit=crop&q=80",
    color: "from-blue-500 to-cyan-500",
    audience: "Affluent travelers, digital nomads, luxury seekers",
  },
  {
    id: "worknai",
    name: "WorknAI Studio",
    handle: "@worknai.media",
    industry: "AI Media Platform",
    voice: "Visionary, Technical, High-Velocity",
    avatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=160&auto=format&fit=crop&q=80",
    color: "from-purple-500 to-pink-500",
    audience: "Creators, CMOs, marketing agencies, founders",
  },
  {
    id: "logixparcel",
    name: "Logix Parcel",
    handle: "@logixparcel",
    industry: "Supply Chain & Logistics",
    voice: "Reliable, Efficient, Metric-driven",
    avatar: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=160&auto=format&fit=crop&q=80",
    color: "from-emerald-500 to-teal-500",
    audience: "E-commerce brands, operations managers, retail leaders",
  },
  {
    id: "pginfo",
    name: "PG Info",
    handle: "@pginfo_tech",
    industry: "Enterprise Cloud & Data",
    voice: "Authoritative, Educational, Insightful",
    avatar: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=160&auto=format&fit=crop&q=80",
    color: "from-blue-600 to-indigo-600",
    audience: "Tech leads, software architects, IT executives",
  },
  {
    id: "zenithtech",
    name: "Zenith Tech",
    handle: "@zenithhardware",
    industry: "Next-Gen AI Hardware",
    voice: "Futuristic, Bold, Groundbreaking",
    avatar: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=160&auto=format&fit=crop&q=80",
    color: "from-amber-500 to-rose-500",
    audience: "Hardware engineers, AI developers, tech enthusiasts",
  },
];

export const contentTypesList: ContentTypeConfig[] = [
  {
    id: "instagram",
    label: "Instagram Post",
    badge: "Carousel & Feed",
    description: "High-engagement captions, image concepts, and curated hashtags.",
    icon: "Instagram",
    gradient: "from-pink-500 to-rose-500",
    glow: "shadow-pink-500/20",
    defaultPrompt: "Create a high-converting Instagram carousel breakdown about 5 hidden flight booking hacks saving over $800 on international business trips.",
    promptSuggestions: [
      "5 Secret Flight Booking Hacks",
      "Behind the scenes luxury cabin tour",
      "Weekend getaway guide under $500",
      "Weekly travel mythbusters carousel",
    ],
  },
  {
    id: "reel",
    label: "AI Reel",
    badge: "9:16 Short-form",
    description: "Hook-driven viral 30s-60s script with pacing, camera notes & audio.",
    icon: "Film",
    gradient: "from-purple-500 to-indigo-500",
    glow: "shadow-purple-500/20",
    defaultPrompt: "Generate a 30-second viral reel script with a strong retention hook exposing why airlines drop seat prices on Tuesday nights at 2 AM.",
    promptSuggestions: [
      "0-3s Pattern interrupt hook",
      "Fast-paced 15s quick tips reel",
      "POV: Flying private for the first time",
      "3 AI tools that replaced my travel agent",
    ],
  },
  {
    id: "youtube",
    label: "YouTube Script",
    badge: "Full Production",
    description: "Complete structured video script with hook, B-roll cues, and CTA.",
    icon: "FileText",
    gradient: "from-red-500 to-amber-500",
    glow: "shadow-red-500/20",
    defaultPrompt: "Write a comprehensive 8-minute YouTube video script comparing autonomous AI customer service vs human luxury concierge support in aviation.",
    promptSuggestions: [
      "The Untold Story of Airline Points",
      "How Modern Jet Engines Actually Work",
      "Complete 2026 Solo Travel Blueprint",
      "Is First Class Ever Worth It?",
    ],
  },
  {
    id: "ad",
    label: "High-Converting Ad",
    badge: "Paid Social Copy",
    description: "Direct-response ad copy with 3 hook variations, angles, and CTA.",
    icon: "Megaphone",
    gradient: "from-blue-500 to-cyan-500",
    glow: "shadow-blue-500/20",
    defaultPrompt: "Craft 3 high-converting Meta and TikTok ad angles promoting our VIP early-bird concierge membership for frequent business travelers.",
    promptSuggestions: [
      "FOMO-based limited seat angle",
      "Problem-agitation-solution (Lost baggage)",
      "Social proof testimonial highlight",
      "Price anchor comparison ad",
    ],
  },
  {
    id: "image",
    label: "AI Image & Graphic",
    badge: "4K Generative",
    description: "Hyper-realistic photorealistic prompt and multi-aspect asset rendering.",
    icon: "Image",
    gradient: "from-emerald-500 to-teal-500",
    glow: "shadow-emerald-500/20",
    defaultPrompt: "Cinematic shot of a luxury private jet interior flying over the Swiss Alps during golden hour sunset, soft ambient cabin illumination, 8K photorealistic, Hasselblad lens.",
    promptSuggestions: [
      "Cyberpunk airport lounge at night",
      "Minimalist 3D isometric travel map",
      "Luxury aviation first class suite 8k",
      "Futuristic supersonic airliner in clouds",
    ],
  },
];

export const generationSteps = [
  "Analyzing target audience and brand tone...",
  "Synthesizing multimodal creative hook...",
  "Applying high-retention storytelling framework...",
  "Generating hashtags and visual pacing...",
  "Polishing final deliverable...",
];

export const initialGeneratedContents: Record<string, GeneratedContent> = {
  instagram: {
    id: "gen-ig-01",
    type: "instagram",
    brand: brandsList[0],
    title: "10 Secret Flight Booking Hacks for Bali Getaways",
    timestamp: "Just now",
    body: `Are you still booking flights the old way? ✈️ Here are 5 airline industry secrets they never advertise:\n\n1. The 54-Day Golden Window: Average international fares reach their mathematical lowest between 45 and 60 days before takeoff.\n2. Split-Ticket Routing: Booking your long-haul leg and domestic hopper through independent carriers often cuts 35% off ticket totals.\n3. Clear Your Geolocation Tokens: Dynamic pricing algorithms adjust fares based on regional purchasing power.\n4. Tuesday Midnight Schedule Flushes: Cancelled hold tickets drop back into booking inventory during weekly database cleanups.\n5. Hidden City Fare Arbitrage: Check layover final destinations before booking direct.\n\nSave this for your next adventure and share with your favorite travel partner! 🌴`,
    hook: "The flight booking hacks airline insiders secretly use.",
    cta: "Save this post & comment 'AIR' for our full 2026 Flight Cheatsheet.",
    hashtags: ["#TravelHacks", "#LuxuryTravel", "#AviationDaily", "#BusinessClass", "#Wanderlust2026", "#GoAirClass"],
    mediaUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=80",
    aspectRatio: "4:5 Portrait",
    metricsEstimated: {
      reach: "48.2K - 65K",
      engagement: "6.8%",
      viralScore: 89,
    },
  },
  reel: {
    id: "gen-reel-01",
    type: "reel",
    brand: brandsList[0],
    title: "Why Airline Seats Drop to 40% Off on Tuesday Nights",
    timestamp: "Just now",
    hook: "Stop booking your flights on Sunday afternoons. You are literally donating $400 to the airline.",
    body: "Fast-paced 35s vertical video script designed for 80%+ 3-second retention and high save velocity.",
    scriptScenes: [
      {
        timestamp: "0:00 - 0:04",
        visual: "Creator looks directly at camera, rapid snap zoom in, holding a digital flight ticket showing an overpriced fare.",
        audio: "'Stop booking your flights on Sunday afternoons. You are literally donating $400 to the airline.'",
      },
      {
        timestamp: "0:04 - 0:14",
        visual: "B-Roll overlay of airport tarmac at dusk, fast screen recording highlighting airline dynamic pricing matrix switching at 2 AM.",
        audio: "'Airlines flush their unconfirmed reservations and corporate hold pools every single Tuesday at midnight.'",
      },
      {
        timestamp: "0:14 - 0:26",
        visual: "Creator points to floating UI overlay showing exact price drop graph: $1,280 down to $710.",
        audio: "'When that happens, the algorithmic pricing engines reset the base inventory tier. If you search between 1 AM and 3 AM, boom — instant 40% savings.'",
      },
      {
        timestamp: "0:26 - 0:35",
        visual: "Close-up smirk, taps phone screen, smooth fade out with glowing WorknAI watermark.",
        audio: "'Comment 'FLIGHT' below and I'll DM you our secret automated fare tracker link. Follow for more.'",
      },
    ],
    hashtags: ["#FlightHacks", "#ReelsViral", "#TravelTikTok", "#Aviation", "#BudgetLuxury"],
    metricsEstimated: {
      reach: "120K - 180K",
      engagement: "9.2%",
      viralScore: 94,
    },
  },
  youtube: {
    id: "gen-yt-01",
    type: "youtube",
    brand: brandsList[1],
    title: "How Autonomous AI Agents Are Transforming Digital Media in 2026",
    timestamp: "Just now",
    hook: "In 2024, AI wrote blog posts. In 2026, autonomous agent networks are running entire media operations from video scripting to real-time programmatic publishing.",
    body: `[0:00 - THE COLD OPEN]\nVisual: High-energy montage of AI generating 4K video clips, rendering audio, and automatically pushing to TikTok and YouTube.\nHost: "What if you could replace a 10-person creative agency with three autonomous agents running 24/7 on autopilot?"\n\n[1:30 - THE BREAKTHROUGH: MULTIMODAL SYNERGY]\nHost breaks down how diffusion models now understand timeline orchestration, brand voice memorization, and real-time audience analytics.\n\n[4:15 - REAL WORLD CASE STUDY]\nExamine how GoAirClass scaled organic reach by 340% without hiring a single video editor.\n\n[7:00 - IMPLEMENTATION BLUEPRINT]\nStep-by-step setup using WorknAI Studio: connecting your brand knowledge base, configuring posting schedules, and fine-tuning creative safety filters.\n\n[9:15 - CALL TO ACTION]\n"Hit subscribe, leave a comment with your brand's biggest bottleneck, and tap the link in the description for free beta access."`,
    cta: "Subscribe for weekly AI production masterclasses & grab the agency starter prompt pack.",
    hashtags: ["#AIAgents", "#NextGenMedia", "#WorknAI", "#Automation2026"],
    metricsEstimated: {
      reach: "25K - 40K",
      engagement: "5.4%",
      viralScore: 82,
    },
  },
  ad: {
    id: "gen-ad-01",
    type: "ad",
    brand: brandsList[0],
    title: "High-Converting Meta & TikTok Ad Copy: VIP Travel Pass",
    timestamp: "Just now",
    hook: "You fly more than 4 times a year. Why are you still paying retail for business class?",
    body: `Headline 1: Never Pay Retail For First Class Again.\nHeadline 2: The Travel Secret Top 1% Executives Use In 2026.\nHeadline 3: Save $3,200 On Your Next Overseas Flight.\n\nPrimary Body:\nStop spending 12 hours refreshing flight comparison engines. GoAirClass Concierge uses predictive machine intelligence to lock in premium cabin upgrades before seats go public.\n\n✓ Zero hidden booking fees\n✓ Instant 24/7 WhatsApp concierge\n✓ Guaranteed lowest international fares or 100% price match refund\n\nOver 18,400 frequent travelers saved an average of $840 per journey this quarter alone.`,
    cta: "Claim Your Free 30-Day VIP Pass → [Book With VIP Perks]",
    hashtags: ["#DirectResponse", "#LuxuryTravelAd", "#FacebookAds", "#PerformanceCreative"],
    metricsEstimated: {
      reach: "85K - 120K",
      engagement: "4.1% CTR",
      viralScore: 91,
    },
  },
  image: {
    id: "gen-img-01",
    type: "image",
    brand: brandsList[0],
    title: "Sunset First Class Lounge - Ultra Photorealistic 4K Asset",
    timestamp: "Just now",
    hook: "8K Photorealistic Architectural Diffusion Rendering",
    body: "Cinematic shot of a futuristic luxury airport lounge with panoramic floor-to-ceiling windows overlooking sleek supersonic jets on a rainy tarmac. Golden hour sunset reflecting on wet asphalt, volumetric dusk lighting, brushed titanium accents, cozy leather armchairs, photorealistic, 8K resolution, octane render, Hasselblad 50mm f/1.2.",
    mediaUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&auto=format&fit=crop&q=80",
    aspectRatio: "16:9 Landscape / 4K UHD",
    metricsEstimated: {
      reach: "High Aesthetic Affinity",
      engagement: "Design Approved",
      viralScore: 96,
    },
  },
};
