require('dotenv').config();
const { Client } = require('pg');

async function run() {
  const url = process.env.DATABASE_URL || ('postgresql://postgres.' + (process.env.SUPABASE_PROJECT_ID || 'azlrpwmernlmovpedhmb') + ':' + encodeURIComponent(process.env.SUPABASE_DB_PASSWORD || '') + '@aws-0-ap-south-1.pooler.supabase.com:6543/postgres');
  const c = new Client({ connectionString: url });
  await c.connect();

  const queries = [
    `CREATE TABLE IF NOT EXISTS public.posts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        type TEXT NOT NULL CHECK (type IN ('reel', 'blog')),
        content TEXT DEFAULT '',
        media_url TEXT,
        thumbnail TEXT,
        status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'published')),
        scheduled_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );`,
    `CREATE TABLE IF NOT EXISTS public.portfolio (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_name TEXT NOT NULL,
        project_title TEXT NOT NULL,
        category TEXT NOT NULL,
        thumbnail TEXT,
        video_url TEXT,
        description TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );`,
    `CREATE TABLE IF NOT EXISTS public.services (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        icon TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );`,
    `CREATE TABLE IF NOT EXISTS public.clients (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        logo TEXT,
        website TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );`,
    `CREATE TABLE IF NOT EXISTS public.leads (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        phone TEXT,
        message TEXT,
        status TEXT DEFAULT 'new',
        created_at TIMESTAMPTZ DEFAULT NOW()
    );`,
    `CREATE TABLE IF NOT EXISTS public.careers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        department TEXT NOT NULL,
        location TEXT NOT NULL,
        description TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );`,
    `NOTIFY pgrst, 'reload schema';`
  ];

  for (const q of queries) {
    try {
      await c.query(q);
    } catch(e) {
      console.log('Query note:', e.message);
    }
  }

  const tables = await c.query("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';");
  console.log('ALL TABLES IN SUPABASE:', tables.rows.map(r => r.table_name));
  await c.end();
}

run().catch(console.error);
